version: '3.4'

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: sqlserver
    environment:
      SA_PASSWORD: "oRe2J4ZabG2Y"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: always

  # api:
  #   build:
  #     context: .
  #     dockerfile: MeuProjeto.API/Dockerfile
  #   depends_on:
  #     - sqlserver
  #   environment:
  #     - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MeuProjetoDB;User Id=sa;Password=YourPassword123!;
  #   ports:
  #     - "5000:80"
